### ISSUE TITLE
rxjs-es d.ts file errors when compiling with tsc --allowJs

### ISSUE THREAD

**Issue by subhaze** [ReactiveX/rxjs#1604]
**RxJS version:**
rxjs-es@5.0.0-beta.5

**Code to reproduce:**
main.js file: `import * as Rx from './node_modules/rxjs-es/Rx';`

tsc cli: `tsc --allowJs --outFile public/main-dist.js --module system public/main.js`

**Expected behavior:**
for tsc compiler to emit Rx code and bundle up into main-dist.js

**Actual behavior:**
tsc compiler errors with the following
```
public/node_modules/rxjs-es/Observable.d.ts(12,6): error TS2304: Cannot find name 'Symbol'.
public/node_modules/rxjs-es/Observable.d.ts(14,86): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/Observable.d.ts(15,42): error TS2304: Cannot find name 'Iterable'.
public/node_modules/rxjs-es/Observable.d.ts(71,60): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/Observable.d.ts(71,70): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/observable/PromiseObservable.d.ts(22,31): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/observable/PromiseObservable.d.ts(23,26): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/operator/toPromise.d.ts(7,59): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/operator/toPromise.d.ts(7,69): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/operator/toPromise.d.ts(9,9): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/operator/toPromise.d.ts(10,26): error TS2304: Cannot find name 'Promise'.
public/node_modules/rxjs-es/operator/toPromise.d.ts(10,36): error TS2304: Cannot find name 'Promise'.
make: *** [build] Error 2
```
and no Rx code is emitted/bundled into main-dist.js

**Additional information:**
If I remove all of the d.ts files that are shipped with rxjs-es everything works correctly. Rx code is emitted and bundled up correctly into main-dist.js

**Comment by kwonoj** [comment]
Related with https://github.com/ReactiveX/rxjs/issues/1066, https://github.com/ReactiveX/rxjs/issues/592 - please include `es6-shim` to support type definitions for ES6, could be done via typings (https://github.com/typings/typings) or manually pulling it down.

Let me close this issue, please feel freely reopen if it's not resolved via es6-shim.

**Comment by subhaze** [comment]
Thanks for the info! It cleared most things up, however, it appears that Observable.d.ts is referencing `/// <reference path="src/symbol/symbol.d.ts" />` in rxjs-es source, but there isn't a file there for symbols that I can see.

Also, is there a reason for adding the d.ts files when emitting the RxJS lib as ES6? Sorry, new to TypeScript and mainly using it as an ES6 -> ES5 transpiler + bundler

**Comment by kwonoj** [comment]
>  it appears that Observable.d.ts is referencing `/// <reference path="src/symbol/symbol.d.ts" />` in rxjs-es source 

: I assume this is previous changes of including symbol definition which is removed in current master.

> Also, is there a reason for adding the d.ts files when emitting the RxJS lib as ES6? 

: It's not about ES2015 consumers, it's for TypeScript consumers and compiler needs to aware type of those implementations, reason why it's type definition (d.ts) instead of implementation.

**Comment by subhaze** [comment]
@kwonoj I'm still having issues with the ES2015 (ES6) code and the included `.d.ts` files. I'm using only `.js` and the `tsc` as the ES2015 -> ES 5 transpiler. This is to, potentially, slowly move into using TypeScript.

I've created a repo with the bare minimum to reproduce this issue, I've added `es6-promise` since the suggested `es6-shim` was giving errors upon trying to install via typings.

Sorry to bug about this, but... I'm just trying to get my head around something that seems "simple" but is proving otherwise with the `.d.ts` files included in the ES2015 code :/

https://github.com/subhaze/rxjs-es_test

Thanks in advance for any help/guidance on this.

**Comment by kwonoj** [comment]
@subhaze 

package.json
```diff
+"prepublish": "typings install",
+"build": "tsc --allowJs -m system --moduleResolution node ./typings/index.d.ts main.js --outFile main-dist.js",
-"build": "tsc --allowJs -m system --moduleResolution node main.js --outFile main-dist.js",
+"devDependencies": {
+   "typings": "^1.0.4"
+}
```

typings.json
```diff
-"dependencies": {
-    "es6-promise": "registry:npm/es6-promise#3.0.0+20160211003958"
-}

+"globalDependencies": {
+    "es6-shim": "registry:dt/es6-shim#0.31.2+20160317120654"
+}
```
