### ISSUE TITLE
Proposal: add a switchScan operator

### ISSUE THREAD

**Issue by lestathc** [ReactiveX/rxjs#2931]
It will be similar as the [mergeScan][rxjs-mergescan] but instead of merging all events of inner observables, if the outer source emitted a new event, it [switch][rxjs-switch] to the recently accumulated inner observable.

[rxjs-mergescan]: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-mergeScan
[rxjs-switch]: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#instance-method-switch

**Comment by kwonoj** [comment]
while it is not concluded yet, we're discussing of plan for mergeScan itself (https://github.com/ReactiveX/rxjs/issues/2737) and for now, we recommend to create operator as user-level first instead of direct addition into core lib. (https://github.com/ReactiveX/rxjs/blob/master/doc/operator-creation.md#diy-custom-operators-for-end-users).

**Comment by kylecordes** [comment]
I have stumbled across a situation where a `switchScan()` would be perfect; implementing it myself does not sound like all that much fun.

**Comment by bradleyayers** [comment]
@kylecordes is your scenario solved by just passing concurrency=1?

**Comment by kylecordes** [comment]
@bradleyayers I'm not sure - I ended up solving the problem I was having a completely different way, with a group operation plus a switch map.

**Comment by benlesh** [comment]
This just came up at Google... I'm going to reopen it.

Here's a minimal implementation in JS: http://jsbin.com/jolaciguvi/1/edit?js,console

**Comment by fljot** [comment]
> Here's a minimal implementation in JS: http://jsbin.com/kiyoyir/3/edit?js,console

@benlesh I think you forgot of disposal of outer subscription in that demo.

**Comment by cartant** [comment]
Closing this in favour of #4442 - which has an associated PR and has been discussed in a core-team meeting.
