### ISSUE TITLE
Error looking for rxjs/operators.js

### ISSUE THREAD

**Issue by bmkleine** [ReactiveX/rxjs#2971]
**RxJS version: 5.5.0 ** 

**Additional information:**
It looks like there is still one place using the old operators file (src/observable/dom/AjaxObservable.ts) line 7: import { map } from '../../operators';

**Comment by nagarajpatil** [comment]
Is this issue fixed?

**Comment by gildebrand** [comment]
We ran into this issue as well, and pinned RxJS to version 5.4.3. This made it work for us again.

**Comment by TovrikTheThird** [comment]
Did the same as @gildebrand but hoping that is just a temporary change and they fix it in 5.5.1 real fast 😬

**Comment by kwonoj** [comment]
anyone mind sharing small repo to test out this failure? I'm trying to look into this now.

**Comment by jasonaden** [comment]
I would be willing to bet this is using SystemJS.

Internally we shouldn't be referring to `rxjs/operators` as it will work in development, but will fail with SystemJS.

**Comment by gildebrand** [comment]
@jasonaden that's correct that this occurs with SystemJS!

**Comment by kwonoj** [comment]
I have pushed fix, there'll be patch release once it's available.

**Comment by nagarajpatil** [comment]
Thanks version 5.4.3 worked for me.

**Comment by zrsio4** [comment]
I've also reverted back to 5.4.3 for now.
I had a similar but different error when I removed rxjs from SystemJS config and added ".../node_modules/rxjs/bundles/Rx.js" script tag to the page header.

**Comment by alan-agius4** [comment]
Having the same problem as well.

**Comment by buu700** [comment]
I'm using webpack (Angular CLI), and all the operator functions are undefined at run-time for me with 5.5.0. Specifically, I'm getting an error when `.first()` is called on a `BehaviorSubject`.

Is this the same bug described here, or should I report it separately?

**Comment by jasonaden** [comment]
@buu700 I think this is a separate issue. If you could file an issue with a reproduction, that would be great.

**Comment by buu700** [comment]
Got it, thanks! Actually, upon further investigation, I'm not sure whether this is an rxjs or Angular bug, so I'll report the details in a ticket there and CC you.

**Comment by shaycraft** [comment]
I had this problem too (fixed by reverting the version) and I am using SystemJS.  Is only WebPack going to be supported in the future?

**Comment by jasonaden** [comment]
@shaycraft Nope. Just waiting for a `5.5.1` release. If you were on `master` SystemJS would be working right now.

**Comment by mlc-mlapis** [comment]
This the file `operators.js` (zipped) that is necessary to temporarily add to `node_modules/rxjs` directory for RxJS 5.5.0 to enable it for using with SystemJS:

[operators.zip](https://github.com/ReactiveX/rxjs/files/1403938/operators.zip)

**Comment by kylecordes** [comment]
I maintain an automatic parallel package of RxJS, which produces a SystemJS bundle: https://www.npmjs.com/package/rxjs-system-bundle

...  and of course it the same problem. I worked around it:

https://github.com/OasisDigital/rxjs-system-bundle/commit/b0f714aa307cb89f14bc6097783c6453674e81d5#diff-0b83f9dedf40d7356e5ca147a077acb4R9

with a (hopefully very temporary) hack consisting of a single `sed` command:

```
sed -e "s/'\./'.\/operators/" <node_modules/rxjs/operators/index.js >node_modules/rxjs/operators.js
```

I don't recommend this, I just did it to keep producing a working bundle. Hopefully the need will evaporate with the upcoming 5.5.1.

**Comment by pe8ter** [comment]
@kylecordes I'm still seeing this issue with my SystemJS bundle on `5.5.1`.

**Comment by babeal** [comment]
@pe8ter no i am seeing the same thing.  They are requiring "operators" which is a folder which isn't allowed.  Only webpack (or other bundler) allows import of folder where it assumes you mean the index.  There is no way for system.js in the client to do this.  This needs to be fixed as it is a breaking change.

**Comment by kylecordes** [comment]
@babeal What you're saying is true of the code as it is arrives from RxJS, but it is possible to work around it, and I have done so with an awful hack that I mentioned a few messages up.  My hack creates the missing operators.ts file. It is ugly but it does work fine. When I get a chance I will post a Plunkr demonstrating it.

**Comment by mlc-mlapis** [comment]
@jasonaden ... did we understand wrongly that version 5.5.1 eliminates the problem with missing `operators.js` file (https://github.com/ReactiveX/rxjs/issues/2971#issuecomment-338316966)?

**Comment by babeal** [comment]
@kylecordes yea thanks.  I hear you it's easy to fix but I don't want to have to do that for the 15 projects I maintain so I will lock to 5.4.x until this is fixed.

**Comment by kylecordes** [comment]
@pe8ter @babeal @mlc-mlapis  Here are the changes in RxJS between 5.5.0 and 5.5.1; I don't think any of these are relevant to our SystemJS operators.ts problem here unfortunately. So I think the @kwonoj fix must have been about a different 5.5.0 glitch.

https://github.com/ReactiveX/rxjs/compare/9538a2024973d9a5c3cbeb26503cc8090dd6b806...0650c52c937cc5153a3d1cc23daf1a689dd921f4

Here is a plunkr which shows my SystemJS redistribution of RxJS in action (look at config.js). Take a look at app.ts to see the operator import.

https://plnkr.co/edit/4Y6KAJ28Wwua8RSVaV8A?p=preview

**Comment by schwede** [comment]
It looks to me like the issue was introduced here: https://github.com/ReactiveX/rxjs/commit/ba2f58686128c910a3391b0ace697b34d8542b78#diff-5fe03a9b5bb68d1a34618cf458d64e1c

Is anyone working on a pull request for this?

**Comment by mlc-mlapis** [comment]
@kylecordes ... shouldn't be `"rxjs/operators/*",` added also?
```
bundles: {
    "npm:rxjs-system-bundle@5.5.0/Rx.system.js": [
      "rxjs",
      "rxjs/*",
      "rxjs/operator/*",
      "rxjs/operators/*",
      "rxjs/observable/*",
      "rxjs/scheduler/*",
      "rxjs/symbol/*",
      "rxjs/add/operator/*",
      "rxjs/add/observable/*",
      "rxjs/util/*"
    ]
}
```

**Comment by mlc-mlapis** [comment]
@kylecordes ... you should also apply `zone-patch-rxjs.js` from `zone.js` because the problem with RxJS scheduler & zone is still not solved in RxJS.

**Comment by kylecordes** [comment]
@mlc-mlapis  I have updated the plunker to make available (although the example doesn't import anything that way), and to apply the `zone-patch-rxjs` patch (although the example run OK without it already). Hopefully having this plunker sitting here linked will help out any passerby who comes along and needs the new lettable operator syntax to work via SystemJS, between now and when a more official fix can be made.

(By the way, this is my favorite kind of open-source contribution... a temporary thing to help fix an interim problem, to be later made obsolete by an upstream project so I won't feel guilt to maintain it forever :-) )

**Comment by ViictorG1** [comment]
So... SystemJS projects doesn't work in this moment? Is there a date to work? I need a solution as soon as possible.

**Comment by mlc-mlapis** [comment]
@ViictorG1 ... RxJS doesn't work even as 5.5.2 ... still the same problem .... but you can use advises above ... it works without any problems using them.

**Comment by ViictorG1** [comment]
@mlc-mlapis at this moment I'm insert operators.js inside dist/node_modules/rxjs but it's so wrong... What you advise to me do?

**Comment by mlc-mlapis** [comment]
@ViictorG1 ... as a permanent solution of course but still working ... I suppose that RxJS 5.5.3 will be there very soon and it'll be the right one for the problem.

**Comment by ViictorG1** [comment]
@mlc-mlapis Ok, thanks, let's wait for permanent solution as soon as possible.

**Comment by sarunint** [comment]
I think inserting this line into SystemJS config should fix this problem:

```
'rxjs/operators': 'npm:rxjs@5.5.2/operators/index.js',
```

**Comment by acrisci** [comment]
workaround:

```
echo 'require('./operators/index.js');' > node_modules/rxjs/operators.js
```

**Comment by pitAlex** [comment]
I did this to make it work:
```
packages: {
    "rxjs/operators" {
         "main": "index.js",
         "defaultExtension": "js"
    }
}
```

**Comment by keithdechant** [comment]
@pitAlex That worked great for me on my Angular 5 app. It's nice to have a workaround that doesn't require editing anything in node_modules.

You're missing a colon after "rxjs/operators", BTW.

**Comment by sarunint** [comment]
This issue is fixed in 5.5.3. All workarounds above can be ignored.

**Comment by paperez** [comment]
I'm getting an error getting operators/refCount.js. Not able to create a plnkr with Angular Material.

**Comment by bevlison** [comment]
I had the error : "looking for rxjs/operators.js", 
when loading an angular TS file : "....service.js" , 
line 3 containing : "import { catchError, map, tap } from 'rxjs/operators';"
line 1 containing : "import { Observable } from 'rxjs/Observable';". That line gives no error! (so rxjs is available)

I don't know how relevant this is, but the solution was not changing version (of rxjs), nor editing the file named "systemjs.config.js", (adding a seperated referal to rxjs/operators, as a post above suggested to do). That systemjs file contains  : "'rxjs': 'npm:rxjs',", which is explaining the availability of eg. rxjs/Observable in angular TS

SOLUTION for me was : changing line 3 in service file to : "import { catchError, map, tap } from 'rxjs/operators/index';" 

EXPLAINED : When checking "./node_modules/rxjs" you won't find a file "operators.js", but you'll find a folder "operators". you could refer to the needed operators, or just all available (choosing for index.js)

Hopefully this solves and explains for others following same tutorials as I'm doing.

**Comment by ChandraTerli** [comment]
I am still having the same issue in Angular 6.0.0? does the issue still exists in latest version?

**Comment by mlc-mlapis** [comment]
@ChandraTerli ... ??? it was the issue with RxJS itself and not with Angular.

**Comment by ChandraTerli** [comment]
Thank you! for the response, I tried your suggestion but got 403 error saying access to is forbidden.

**Comment by ChandraTerli** [comment]
this is what I is in my Package.Json... "rxjs": "6.1.0" and in SystemJs.Config..,
      'rxjs/operators': {
          'main': 'index.js',
          'defaultExtension': 'js'
      }

**Comment by ChandraTerli** [comment]
and I get this error..
http://localhost:41211/node_modules/rxjs/ 403 (Forbidden)

**Comment by mlc-mlapis** [comment]
@ChandraTerli ... but the error is related to `rxjs` and not to `rxjs/operators`:

http://localhost:41211/node_modules/rxjs/ 403 (Forbidden)

Are you importing what when the error appears?

**Comment by mlc-mlapis** [comment]
@ChandraTerli ... it looks that you use SystemJS in the project. Is it an older app? And you want to migrate to Angular 6 now? Then I recommend you to start with a fresh project and with Angular CLI and migrate you previous app step by step.

**Comment by ShinDarth** [comment]
I'm having a similar issue since rxjs 6:

> GET https://unpkg.com/rxjs@6.2.1/operators.js 404 ()
> previewer.483de356abd4ac4365bd.js:1 Error: (SystemJS) Error: XHR error (404) loading https://unpkg.com/rxjs/operators.js
> 	    at XMLHttpRequest.wrapFn (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1188:39)
> 	    at ZoneDelegate.invokeTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:421:31)
> 	    at Zone.runTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:188:47)
> 	    at ZoneTask.invokeTask [as invoke] (https://unpkg.com/zone.js@0.8.26/dist/zone.js:496:34)
> 	    at invokeTask (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1540:14)
> 	    at XMLHttpRequest.globalZoneAwareCallback (https://unpkg.com/zone.js@0.8.26/dist/zone.js:1566:17)
> 	Error loading https://unpkg.com/rxjs/operators.js as "rxjs/operators" from https://unpkg.com/@angular/core/bundles/core.umd.js

**Comment by ursseenu71** [comment]
@ShinDarth did you find a fix for the error you posted? I am getting the same error with rxjs 6, angular 6. Appreciate your help if you can give me some pointers on how this can be fixed.

**Comment by ShinDarth** [comment]
not yet

**Comment by ShinDarth** [comment]
@ursseenu71 FYI: I've raised a question here: https://stackoverflow.com/questions/51288263/plunker-error-get-https-unpkg-com-rxjs6-2-1-operators-js-404

I'll post the solution there in case I find one.

**Comment by mlc-mlapis** [comment]
@ShinDarth ... entry point for an operator is `rxjs/operators` ... not 'rxjs'.
