### ISSUE TITLE
5.5.3  EmptyError: no elements in sequence

### ISSUE THREAD

**Issue by huineng** [ReactiveX/rxjs#3151]
**RxJS version:**
5.5.3

**Code to reproduce:**
since my update to 5.5.3  i'm getting errors in otherwise perfectly fine running angular 5.x application

this is the error i'm getting this morning 

all was working perfectly prior to 5.5.3

difficult for me to trap what the reason could be thanks

```
Error: Uncaught (in promise): EmptyError: no elements in sequence
EmptyError: no elements in sequence
    at new EmptyError (EmptyError.js:27)
    at FirstSubscriber._complete (first.js:154)
    at FirstSubscriber.Subscriber.complete (Subscriber.js:121)
    at MergeMapSubscriber._complete (mergeMap.js:144)
    at MergeMapSubscriber.Subscriber.complete (Subscriber.js:121)
    at MapSubscriber.Subscriber._complete (Subscriber.js:139)
    at MapSubscriber.Subscriber.complete (Subscriber.js:121)
    at EmptyObservable._subscribe (EmptyObservable.js:82)
    at EmptyObservable.Observable._trySubscribe (Observable.js:173)
    at EmptyObservable.Observable.subscribe (Observable.js:161)
    at new EmptyError (EmptyError.js:27)
    at FirstSubscriber._complete (first.js:154)
    at FirstSubscriber.Subscriber.complete (Subscriber.js:121)
    at MergeMapSubscriber._complete (mergeMap.js:144)
    at MergeMapSubscriber.Subscriber.complete (Subscriber.js:121)
    at MapSubscriber.Subscriber._complete (Subscriber.js:139)
    at MapSubscriber.Subscriber.complete (Subscriber.js:121)
    at EmptyObservable._subscribe (EmptyObservable.js:82)
    at EmptyObservable.Observable._trySubscribe (Observable.js:173)
    at EmptyObservable.Observable.subscribe (Observable.js:161)
    at AppErrorHandler.handleError (app.exception.ts:47)
    at Object.next (core.js:5377)
    at SafeSubscriber.schedulerFn [as _next] (core.js:4223)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:246)
    at SafeSubscriber.next (Subscriber.js:193)
    at Subscriber._next (Subscriber.js:132)
    at Subscriber.next (Subscriber.js:96)
    at EventEmitter.Subject.next (Subject.js:63)
    at EventEmitter.emit (core.js:4203)
    at core.js:4652
```

**Comment by hugograf** [comment]
After an update of my angular project I get the same error. In my case, routing with children and outlets doesn't work.

**Comment by thisisgit** [comment]
Experiencing the same thing. Had to fix rxjs version in package.json to prevent CI from installing version 5.5.3: `"rxjs": "5.5.2"`

**Comment by ajmarmar** [comment]
HI,

I've the same error.

**Comment by Cito** [comment]
Me too with an Angular 5.0.5 project. After downgrading rxjs to 5.5.2 the problem went away.

**Comment by Cito** [comment]
See [Angular issue #20752](https://github.com/angular/angular/issues/20752) for a minimal reproduction of the problem.

**Comment by rodrigodata** [comment]
@Cito that solved!

**Comment by locomotif** [comment]
FYI: In react project,  v5.5.3 upgrade also breaking app.  In this case `import Rx from 'rxjs/Rx'` is returning undefined; producing `TypeError: Cannot read property 'Subject' of undefined`.  This was functioning fine prior to to this minor release.

**Comment by kwonoj** [comment]
I'll try to look into this shortly.

**Comment by aitboudad** [comment]
+ I noticed a small regression in bundle size ~10kb when upgrade from `5.5.2` -> `5.5.3`

**Comment by zimme** [comment]
This is breaking prettier/prettier-eslint-cli as we're doing `import Rx from "rxjs/Rx";` which is now returning `undefined´ so we can't access `Rx.Observable....`.

**Comment by kwonoj** [comment]
We have added quick fix for this and patch will be released soon.

**Comment by rfanjul** [comment]
I got the error also with 5.5.3 , does it already work ?

**Comment by dhabierre** [comment]
This can help (using rxjs 5.5.3 - "rxjs": "^5.5.2")

Bug with empty path:

const routes: Routes = [
    { path: "", component: SynthesisComponent },
    { path: "home", component: SynthesisComponent },
    { path: "about", component: AboutComponent },
    ...
];

Ok when using pathMatch: 'full':

const routes: Routes = [
    { pathMatch: 'full', path: "", component: SynthesisComponent },
    { pathMatch: 'full', path: "home", component: SynthesisComponent },
    { pathMatch: 'full', path: "about", component: AboutComponent },
    ...
];

**Comment by mixalistzikas** [comment]
Is this a temporary solution or a standard solution? Are you going to release a bug fix?

**Comment by vishwass** [comment]
Fixed this issue in my setup by changing rxjs from ^5.4.2 to 5.5.2.

**Comment by cracautanu** [comment]
quick fix tested in 2 projects - in package.json replace "rxjs": "^5.5.2" or "rxjs": "^5.5.3" with "rxjs": "5.5.2"

**Comment by SivaPrasanna45** [comment]
ERROR Error: Uncaught (in promise): EmptyError: no elements in sequence
EmptyError: no elements in sequence
    at new EmptyError (EmptyError.js:28)
    at FirstSubscriber._complete (first.js:154)
    at FirstSubscriber.Subscriber.complete (Subscriber.js:122)
    at MergeMapSubscriber._complete (mergeMap.js:150)
    at MergeMapSubscriber.Subscriber.complete (Subscriber.js:122)
    at MapSubscriber.Subscriber._complete (Subscriber.js:140)
    at MapSubscriber.Subscriber.complete (Subscriber.js:122)
    at EmptyObservable._subscribe (EmptyObservable.js:83)
    at EmptyObservable.Observable._trySubscribe (Observable.js:172)
    at EmptyObservable.Observable.subscribe (Observable.js:160)
    at new EmptyError (EmptyError.js:28)
    at FirstSubscriber._complete (first.js:154)
    at FirstSubscriber.Subscriber.complete (Subscriber.js:122)
    at MergeMapSubscriber._complete (mergeMap.js:150)
    at MergeMapSubscriber.Subscriber.complete (Subscriber.js:122)
    at MapSubscriber.Subscriber._complete (Subscriber.js:140)
    at MapSubscriber.Subscriber.complete (Subscriber.js:122)
    at EmptyObservable._subscribe (EmptyObservable.js:83)
    at EmptyObservable.Observable._trySubscribe (Observable.js:172)
    at EmptyObservable.Observable.subscribe (Observable.js:160)
    at resolvePromise (zone.js:824)
    at resolvePromise (zone.js:795)
    at eval (zone.js:873)
    at ZoneDelegate.invokeTask (zone.js:425)
    at Object.onInvokeTask (core.js:4621)
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:192)
    at drainMicroTaskQueue (zone.js:602)
    at ZoneTask.invokeTask [as invoke] (zone.js:503)
    at invokeTask (zone.js:1540)


I want solve this problem with RxJS5.5.3 only, is there any solution for that?

**Comment by johnedvard** [comment]
I am getting the same error when I press an anchor element, and the anchor element is using `[routerLink]="'somePath'"`. I do not know if this is limited to anchor tags or not. I am using `rxjs:5.2.2`, as suggested by some others, but I am still receiving errors.

**Comment by wooltar** [comment]
I have had same problem. It was because I was using a modal from ng2-bootstrap-modal.
`import { BootstrapModalModule } from 'ng2-bootstrap-modal';
`
 If this is your case. Try use forRoot and pathMatch:'full' to the routes in the router module

>  ModalModule.forRoot(),

**Comment by MarcusCalidus** [comment]
Please try `rxjs@5.5.4` it fixed my issues

**Comment by kingo999** [comment]
5.5.4 works

**Comment by mmanavaz** [comment]
I'm still getting the same issue. I downgraded to 5.5.2 and also tried 5.5.4...both are not working for me.

**Comment by lixing0323** [comment]
update to 5.5.5 is ok.

**Comment by mmanavaz** [comment]
Tried 5.5.5 as you suggested- still getting the same error...

**Comment by beeman** [comment]
@mmanavaz make sure to remove your node_modules and reinstall the dependencies after you changed the versions. If that does not help, try clearing your npm cache.

**Comment by mmanavaz** [comment]
I was able to get it working, thank you @beeman

**Comment by zee92** [comment]
I just resolved it by removing its cap ^ from  "rxjs": "^5.5.2", to  "rxjs": "5.5.2",

**Comment by tcozzens** [comment]
I am still having this issue - on "version": "5.5.6" of rxjs and Angular 5.2.10. I have also tried the pathMatch: 'full' as well and it still does not work...
