### ISSUE TITLE
`defer` operator inner-observable execute after the related outer-observable has been unsubscribed from

### ISSUE THREAD

**Issue by peaBerberian** [ReactiveX/rxjs#4025]
## Bug Report

**Current Behavior**

Deferred inner-observables continue to execute even when the outer observable it depends on has no subscription left. This was seen only with a non-asynchronous Scheduler.
 
Please forgive me if it's not an issue in your opinion, but after giving it some thought I don't really see any advantage to this behavior.

**Reproduction**

Running:
```js
const {
  Subject,
  of: obsOf,
  concat: obsConcat,
  defer,
} = require("rxjs");
const {
  finalize,
  mergeMap,
  tap,
  takeUntil,
} = require("rxjs/operators");

const subject = new Subject();

obsOf(null).pipe(
  mergeMap(() =>
    obsConcat(
      defer(() => {
        console.log("side-effect 1");
        return obsOf(1);
      }),
      defer(() => {
        console.log("side-effect 2");
        return obsOf(2);
      }),
      defer(() => { // This should never be run
        console.log("side-effect 3");
        return obsOf(3);
      })
    )
  ),
  finalize(() => {
    console.log("finalized");
  })
)
.pipe(
  takeUntil(subject),
  tap((i) => {
    if (i === 2) { // Stop subscribing when `2` is emitted
      subject.next();
    }
  })
).subscribe(
  (i) => { console.log("next", i); },
  (e) => { console.log("error", e); },
  () => { console.log("complete"); },
);
```
Outputs:
```sh
side-effect 1
next 1
side-effect 2
complete
finalized
side-effect 3
```
As you can see, the `side-effect 3` line is displayed even after the outer-observable has no subscription left.

**Expected behavior**

I would expect that any deferred observable running after unsubscription would not be run.

That is, obtaining the following output from the previous code:
```sh
side-effect 1
next 1
side-effect 2
complete
finalized
```
_(no `side-effect 3` line)_

As the item(s) emitted from those observables would never be used, I don't see any advantage to "running" them.

Moreover, using something like an AsapScheduler do not run the deferred observable. 

**Environment**
- Runtime: Node v10.8.0
- RxJS version: 6.2.2

**Comment by cartant** [comment]
It's possible that this could have been fixed in https://github.com/ReactiveX/rxjs/pull/3963. Would you be able to investigate whether or not the problem is reproducible with the current `master`?

**Comment by peaBerberian** [comment]
It seems to have been fixed on master, yes.
Thanks a lot!

Any idea when this version is going to be released?

**Comment by peaBerberian** [comment]
Actually, although it now works with ``mergeMap`` and ``concatMap``, I still do have the exact same issue when I use a ``switchMap`` or ``exhaustMap``.

My observables are still run post-unsubscription.

Example with a ``switchMap``, runnable directly in node:
```js
const {
  Subject,
  of: obsOf,
  concat: obsConcat,
  defer,
} = require("rxjs");
const {
  finalize,
  switchMap,
  tap,
  takeUntil,
} = require("rxjs/operators");

const subject = new Subject();

obsOf(null).pipe(
  switchMap(() =>
    obsConcat(
      defer(() => {
        console.log("side-effect 1");
        return obsOf(1);
      }),
      defer(() => {
        console.log("side-effect 2");
        return obsOf(2);
      }),
      defer(() => { // This should never be run
        console.log("side-effect 3");
        return obsOf(3);
      })
    )
  ),
  finalize(() => {
    console.log("finalized");
  })
)
.pipe(
  takeUntil(subject),
  tap((i) => {
    if (i === 2) { // Stop subscribing when `2` is emitted
      subject.next();
    }
  })
).subscribe(
  (i) => { console.log("next", i); },
  (e) => { console.log("error", e); },
  () => { console.log("complete"); },
);
```
Here, the ``side-effect 3`` line still appears.

_Note that as there is a single emit in my example (``obsOf(null)``, ``mergeMap``, ``switchMap``, ``concatMap`` and ``exhaustMap`` should show here the same behavior here_

**Comment by peaBerberian** [comment]
I just found the problem, it's because some ``OuterSubscriber``s such as the ``SwitchMapSubscriber`` calls ``this.add`` after calling ``subscribeToResult`` (more specifically, the former is executed with the return value of the later on the same line).

If an unsubscription from that observable happens synchronously after subscription, like in my example, the ``OuterSubscriber`` (``switchMap`` here) would thus not have added the ``InnerSubscriber`` (``concat``) to its ``_subscriptions`` array in time when the teardown logic happens.

We do not have the problem with ``mergeMap``, or in any operator which rely on the ``MergeMapSubscriber`` (like ``concatMap``) because the problem was fixed on this operator in the commit https://github.com/ReactiveX/rxjs/commit/40852ff71.

In particular in those lines: https://github.com/ReactiveX/rxjs/commit/40852ff71#diff-7b6bd39b2a4a4fa626a8beeea9258399L142, we can see that we now have a ``InnerSubscriber`` created before ``subscribeToResult``. This allows us to call ``this.add`` on it just before.

Because the fix looks pretty straightforward, I'm looking into doing a PR fixing that problem - and the corresponding tests - very soon (I guess tomorrow if I have time, or on monday). What do you think?

**Comment by cartant** [comment]
I think you are correct. And a PR would be much appreciated.

**Comment by cartant** [comment]
Closing this as the related PR has been merged.
